name: Waka Readme

on:
  workflow_dispatch: # Tombol untuk menjalankan manual
  schedule:
    - cron: '0 0 * * *' # Menjalankan setiap tengah malam

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIMw_API_KET }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
