name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    permissions: # <-- TAMBAHKAN BLOK INI
      contents: write # <-- DAN BARIS INI
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIMW_API_KET }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ... sisa opsi Anda
